package io.jmaciel.banking;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@AllArgsConstructor
@Getter
@ToString
public enum Bank {

  BANCO_DO_BRASIL("001", "Banco do Brasil S.A."),
  BANCO_DA_AMAZONIA("003", "Banco da Amazônia S.A."),
  BANCO_DO_NORDESTE("004", "Banco do Nordeste do Brasil S.A."),
  BANCO_STANDARD_DE_INVESTIMENTOS("012", "Banco Standard de Investimentos S.A."),
  NATIXIS_BRASIL("014", "Natixis Brasil S.A. Banco Múltiplo"),
  BANCO_AZTECA("019", "Banco Azteca do Brasil S.A."),
  BANESTES("021", "Banestes S.A. Banco do Estado do Espírito Santo"),
  BANCO_BANDEPE("024", "Banco de Pernambuco S.A. - Bandepe"),
  BANCO_ALFA("025", "Banco Alfa S.A."),
  BANCO_BANERJ("029", "Banco Banerj S.A."),
  BANCO_BEG("031", "Banco BEG S.A."),
  BANCO_SANTANDER("033", "Banco Santander (Brasil) S.A."),
  BANCO_BRADESCO_BBI("036", "Banco Bradesco BBI S.A."),
  BANCO_DO_ESTADO_DO_PARA("037", "Banco do Estado do Pará S.A."),
  BANCO_CARGILL("040", "Banco Cargill S.A."),
  BANCO_DO_ESTADO_DO_RIO_GRANDE_DO_SUL("041", "Banco do Estado do Rio Grande do Sul S.A."),
  BANCO_BVA("044", "Banco BVA S.A."),
  BANCO_OPPORTUNITY("045", "Banco Opportunity S.A."),
  BANCO_DO_ESTADO_DE_SERGIPE("047", "Banco do Estado de Sergipe S.A."),
  HIPERCARD("062", "Hipercard Banco Múltiplo S.A."),
  BANCO_IBI("063", "Banco Ibi S.A. - Banco Múltiplo"),
  BANCO_LEMON("065", "Banco Lemon S.A."),
  BANCO_MORGAN_STANLEY("066", "Banco Morgan Stanley S.A."),
  BPN_BRASIL("069", "BPN Brasil Banco Múltiplo S.A."),
  BRB("070", "BRB - Banco de Brasília S.A."),
  BANCO_RURAL_MAIS("072", "Banco Rural Mais S.A."),
  BB_BANCO_POPULAR("073", "BB Banco Popular do Brasil S.A."),
  BANCO_J_SAFRA("074", "Banco J. Safra S.A."),
  BANCO_CR2("075", "Banco CR2 S/A"),
  BANCO_KDB("076", "Banco KDB do Brasil S.A."),
  BANCO_INTERMEDIUM("077", "Banco Intermedium S/A"),
  BES_INVESTIMENTO("078", "BES Investimento do Brasil S.A. - Banco de Investimento"),
  JBS_BANCO("079", "JBS Banco S/A"),
  CONCORDIA_BANCO("081", "Concórdia Banco S.A."),
  BANCO_TOPAZIO("082", "Banco Topázio S.A."),
  BANCO_DA_CHINA("083", "Banco da China Brasil S.A."),
  BANCO_BMF("096", "Banco BM&F de Serviços de Liquidação e Custódia S.A."),
  CAIXA_ECONOMICA_FEDERAL("104", "Caixa Econômica Federal"),
  BANCO_BBM("107", "Banco BBM S/A"),
  BANCO_NOSSA_CAIXA("151", "Banco Nossa Caixa S.A."),
  BANCO_ITAU_BBA("184", "Banco Itaú BBA S.A."),
  BANCO_BRADESCO_CARTOES("204", "Banco Bradesco Cartões S.A."),
  BANCO_UBS_PACTUAL("208", "Banco UBS Pactual S.A."),
  BANCO_MATONE("212", "Banco Matone S.A."),
  BANCO_ARBI("213", "Banco Arbi S.A."),
  BANCO_DIBENS("214", "Banco Dibens S.A."),
  BANCO_SUDAMERIS("215", "Banco Comercial e de Investimento Sudameris S.A."),
  BANCO_JOHN_DEERE("217", "Banco John Deere S.A."),
  BANCO_BONSUCESSO("218", "Banco Bonsucesso S.A."),
  BANCO_CALYON("222", "Banco Calyon Brasil S.A."),
  BANCO_FIBRA("224", "Banco Fibra S.A."),
  BANCO_BRASCAN("225", "Banco Brascan S.A."),
  BANCO_CRUZEIRO_DO_SUL("229", "Banco Cruzeiro do Sul S.A."),
  UNICARD("230", "Unicard Banco Múltiplo S.A."),
  BANCO_GE_CAPITAL("233", "Banco GE Capital S.A."),
  BANCO_BRADESCO("237", "Banco Bradesco S.A."),
  BANCO_CLASSICO("241", "Banco Clássico S.A."),
  BANCO_MAXIMA("243", "Banco Máxima S.A."),
  BANCO_ABC_BRASIL("246", "Banco ABC Brasil S.A."),
  BANCO_BOAVISTA_INTERATLANTICO("248", "Banco Boavista Interatlântico S.A."),
  BANCO_INVESTCRED_UNIBANCO("249", "Banco Investcred Unibanco S.A."),
  BANCO_SCHAHIN("250", "Banco Schahin S.A."),
  PARANA_BANCO("254", "Paraná Banco S.A."),
  BANCO_CACIQUE("263", "Banco Cacique S.A."),
  BANCO_FATOR("265", "Banco Fator S.A."),
  BANCO_CEDULA("266", "Banco Cédula S.A."),
  BANCO_LA_NACION_ARGENTINA("300", "Banco de La Nacion Argentina"),
  BANCO_BMG("318", "Banco BMG S.A."),
  BANCO_INDUSTRIAL_E_COMERCIAL("320", "Banco Industrial e Comercial S.A."),
  BANCO_ITAU("341", "Banco Itaú S.A."),
  BANCO_SOCIETE_GENERALE("366", "Banco Societe Generale Brasil S.A."),
  BANCO_WESTLB("370", "Banco WestLB do Brasil S.A."),
  BANCO_JP_MORGAN("376", "Banco J.P. Morgan S.A."),
  BANCO_MERCANTIL("389", "Banco Mercantil do Brasil S.A."),
  BANCO_FINASA_BMC("394", "Banco Finasa BMC S.A."),
  HSBC_BANK("399", "HSBC Bank Brasil S.A. - Banco Múltiplo"),
  UNIBANCO("409", "Unibanco-União de Bancos Brasileiros S.A."),
  BANCO_CAPITAL("412", "Banco Capital S.A."),
  BANCO_SAFRA("422", "Banco Safra S.A."),
  BANCO_RURAL("453", "Banco Rural S.A."),
  BANCO_TOKYO_MITSUBISHI_UFJ("456", "Banco de Tokyo-Mitsubishi UFJ Brasil S/A"),
  BANCO_SUMITOMO_MITSUI("464", "Banco Sumitomo Mitsui Brasileiro S.A."),
  BANCO_CAIXA_GERAL("473", "Banco Caixa Geral - Brasil S.A."),
  CITIBANK("477", "Citibank N.A."),
  BANCO_ITAUBANK("479", "Banco Itaubank S.A."),
  DEUTSCHE_BANK("487", "Deutsche Bank S.A. - Banco Alemão"),
  JPMORGAN_CHASE("488", "JPMorgan Chase Bank, National Association"),
  ING_BANK("492", "ING Bank N.V."),
  BANCO_REPUBLICA_ORIENTAL_URUGUAY("494", "Banco de La Republica Oriental del Uruguay"),
  BANCO_PROVINCIA_BUENOS_AIRES("495", "Banco de La Provincia de Buenos Aires"),
  BANCO_CREDIT_SUISSE("505", "Banco Credit Suisse (Brasil) S.A."),
  BANCO_LUSO_BRASILEIRO("600", "Banco Luso Brasileiro S.A."),
  BANCO_INDUSTRIAL("604", "Banco Industrial do Brasil S.A."),
  BANCO_VR("610", "Banco VR S.A."),
  BANCO_PAULISTA("611", "Banco Paulista S.A."),
  BANCO_GUANABARA("612", "Banco Guanabara S.A."),
  BANCO_PECUNIA("613", "Banco Pecunia S.A."),
  BANCO_PANAMERICANO("623", "Banco Panamericano S.A."),
  BANCO_FICSA("626", "Banco Ficsa S.A."),
  BANCO_INTERCAP("630", "Banco Intercap S.A."),
  BANCO_RENDIMENTO("633", "Banco Rendimento S.A."),
  BANCO_TRIANGULO("634", "Banco Triângulo S.A."),
  BANCO_SOFISA("637", "Banco Sofisa S.A."),
  BANCO_PROSPER("638", "Banco Prosper S.A."),
  BANCO_ALVORADA("641", "Banco Alvorada S.A."),
  BANCO_PINE("643", "Banco Pine S.A."),
  ITAU_UNIBANCO("652", "Itaú Unibanco Banco Múltiplo S.A."),
  BANCO_INDUSVAL("653", "Banco Indusval S.A."),
  BANCO_AJ_RENNER("654", "Banco A.J. Renner S.A."),
  BANCO_VOTORANTIM("655", "Banco Votorantim S.A."),
  BANCO_DAYCOVAL("707", "Banco Daycoval S.A."),
  BANIF_BANCO("719", "Banif - Banco Internacional do Funchal (Brasil), S.A."),
  BANCO_CREDIBEL("721", "Banco Credibel S.A."),
  BANCO_GERDAU("734", "Banco Gerdau S.A."),
  BANCO_POTTENCIAL("735", "Banco Pottencial S.A."),
  BANCO_MORADA("738", "Banco Morada S.A."),
  BANCO_BGN("739", "Banco BGN S.A."),
  BANCO_BARCLAYS("740", "Banco Barclays S.A."),
  BANCO_RIBEIRAO_PRETO("741", "Banco Ribeirão Preto S.A."),
  BANCO_SEMEAR("743", "Banco Semear S.A."),
  BANCO_CITIBANK("745", "Banco Citibank S.A."),
  BANCO_MODAL("746", "Banco Modal S.A."),
  BANCO_RABOBANK("747", "Banco Rabobank International Brasil S.A."),
  BANCO_COOPERATIVO_SICREDI("748", "Banco Cooperativo Sicredi S.A."),
  BANCO_SIMPLES("749", "Banco Simples S.A."),
  DRESDNER_BANK("751", "Dresdner Bank Brasil S.A. Banco Múltiplo"),
  BANCO_BNP_PARIBAS("752", "Banco BNP Paribas Brasil S.A."),
  NBC_BANK("753", "NBC Bank Brasil S. A. - Banco Múltiplo"),
  SICOOB("756", "Banco Cooperativo do Brasil S.A. - Bancoob"),
  BANCO_KEB("757", "Banco KEB do Brasil S.A.");

  private final String code;
  private final String name;

}
